name: mera_mera_bot
description: A sample command-line application.
version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.18.2 <3.0.0'

# dependencies:
#   path: ^1.8.0

dev_dependencies:
  build_runner: ^2.2.1
  freezed: ^2.1.1
  json_serializable: ^6.5.0
  lints: ^2.0.0
  test: ^1.16.0
dependencies:
  freezed_annotation: ^2.1.0
  json_annotation: ^4.7.0
  http: ^0.13.5
  teledart: ^0.3.4
  universal_html: ^2.0.8
  youtube_explode_dart: ^1.12.1
